name: "CIFAR100-ResNet"
training:
  ID: "ClassificationTrainer"

  epochs: 200
  lr: 0.1
  batch_size: 64

  optimizer: "sgd"
  optimizer_cfg:
    momentum: 0.9
    weight_decay: 0.0005
  lr_scheduler: "cosine"
  lr_scheduler_cfg: {}

validation:
  batch_size: 64
  metrics:

model:
  TYPE: "custom"
  ID: "ClassificationModel"

  backbone:
    cfg:
      low_res: True
  modules:
    classifier:
      name: ClassificationHead
      input: "output"
      args:
        reduction: "gap"
        dropout: 0.2
        num_classes: 100
        return_logits: True # return logits instead of softmax probability.
    loss_fn:
      name: "CrossEntropyLoss"

