
training:
  mixup_cutmix:
    mixup_alpha: 0.0 # cumix only
    cutmix_alpha: 1.0
    cutmix_minmax: null
    prob: 1.0
    switch_prob: 0.5
    mode: 'batch'
    correct_lam: True
    label_smoothing: 0.1
    num_classes: 5
