# implement mixup_fn implemented in timm
# both mixup & cutmix are active, hyperparameters are equal as described in:
# Solving ImageNet: a Unified Scheme for Training any Backbone to Top Results, 2022

training:
  mixup_cutmix:
    mixup_alpha: .8
    cutmix_alpha: 1.0
    cutmix_minmax: null
    prob: 1.0
    switch_prob: 0.5
    mode: 'batch'
    correct_lam: True
    label_smoothing: 0.0
    num_classes: 5
